/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as TaiKhoanRouteImport } from './routes/tai-khoan'
import { Route as AppSkillIdRouteImport } from './routes/app.$skillId'
import { Route as SkillSkillIdRouteImport } from './routes/skill.$skillId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiKhoanRoute = TaiKhoanRouteImport.update({
  id: '/tai-khoan',
  path: '/tai-khoan',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSkillIdRoute = AppSkillIdRouteImport.update({
  id: '/app/$skillId',
  path: '/app/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillSkillIdRoute = SkillSkillIdRouteImport.update({
  id: '/skill/$skillId',
  path: '/skill/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/app/$skillId': typeof AppSkillIdRoute
  '/skill/$skillId': typeof SkillSkillIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/app/$skillId': typeof AppSkillIdRoute
  '/skill/$skillId': typeof SkillSkillIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/app/$skillId': typeof AppSkillIdRoute
  '/skill/$skillId': typeof SkillSkillIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/tai-khoan' | '/app/$skillId' | '/skill/$skillId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/tai-khoan' | '/app/$skillId' | '/skill/$skillId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/tai-khoan'
    | '/app/$skillId'
    | '/skill/$skillId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  TaiKhoanRoute: typeof TaiKhoanRoute
  AppSkillIdRoute: typeof AppSkillIdRoute
  SkillSkillIdRoute: typeof SkillSkillIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-khoan': {
      id: '/tai-khoan'
      path: '/tai-khoan'
      fullPath: '/tai-khoan'
      preLoaderRoute: typeof TaiKhoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$skillId': {
      id: '/app/$skillId'
      path: '/app/$skillId'
      fullPath: '/app/$skillId'
      preLoaderRoute: typeof AppSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill/$skillId': {
      id: '/skill/$skillId'
      path: '/skill/$skillId'
      fullPath: '/skill/$skillId'
      preLoaderRoute: typeof SkillSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  TaiKhoanRoute: TaiKhoanRoute,
  AppSkillIdRoute: AppSkillIdRoute,
  SkillSkillIdRoute: SkillSkillIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
